environment                      = "development"
project_id                       = "govuk-knowledge-graph-dev"
project_number                   = "628722085506"
govgraph_domain                  = "govgraphdev.dev"
govgraph_static_ip_address       = "34.89.100.153"
govgraphsearch_domain            = "govgraphsearchdev.dev"
application_title                = "GovGraph Search (development)"
