environment           = "production"
project_id            = "govuk-knowledge-graph"
project_number        = "19513753240"
govgraph_domain       = "govgraph.dev"
govgraphsearch_domain = "govgraphsearch.dev"
govsearch_domain      = "gov-search.service.gov.uk"
application_title     = "GovGraph Search"
