source "https://rubygems.org"

gem "functions_framework"
gem "json"
gem "pandoc-ruby"

group :development, :test do
  gem "byebug", require: true
  gem "rspec"
  gem "rubocop"
  gem "rubocop-govuk", require: false
end
