environment                      = "staging"
project_id                       = "govuk-knowledge-graph-staging"
project_number                   = "957740527277"
govgraph_domain                  = "govgraphstaging.dev"
govgraph_static_ip_address       = "35.189.74.112"
govgraphsearch_static_ip_address = "35.189.74.112"
