environment           = "staging"
project_id            = "govuk-knowledge-graph-staging"
project_number        = "957740527277"
govgraph_domain       = "govgraphstaging.dev"
govgraphsearch_domain = "govgraphsearchstaging.dev"
govsearch_domain      = "NOT_IN_USE"
application_title     = "GovGraph Search (staging)"
