# Based on Debian for convenience, rather than for small size.
# Includes all gcloud components.

FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:456.0.0

RUN apt-get update && apt-get install -y redis-tools jq
