source "https://rubygems.org"

gem "functions_framework", "1.6.0"
gem "json", "2.10.2"
gem "nokogiri", "1.18.4"

group :development, :test do
  gem "byebug", require: true
  gem "rspec"
  gem "rubocop"
  gem "rubocop-govuk", require: false
end
