name: Python Lint and Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docker/embed-text/**'

defaults:
  run:
    working-directory: docker/embed-text

env:
  MODEL_PATH: model

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.6'

    - name: Check code formatting with Black
      run: |
        pip install black
        black --check .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Download the model
      run: |
        python download-model.py

    - name: Run PyTest
      run: pytest .
