name: rds-parquet-bq-loader lint and test

on:
  pull_request:
    paths:
      - "docker/rds-parquet-bq-loader/**"
      - ".github/workflows/rds-parquet-bq-loader-lint-and-test.yml"

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    # Set default execution directory for all `run` steps
    defaults:
      run:
        working-directory: docker/rds-parquet-bq-loader

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          # Specify the lockfile path explicitly when outside the root directory
          cache-dependency-path: "docker/rds-parquet-bq-loader/requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt

      - name: Lint code with Ruff
        run: |
          ruff check .

      - name: Run tests with Pytest
        run: |
          python -m pytest
